version: '3.8'

networks:
  roboshop:
    driver: bridge

services:
  mongodb:
    image: mongodb:v1
    container_name: mongodb
    networks:
      - roboshop

  catalogue:
    image: catalogue:v1
    container_name: catalogue
    networks:
      - roboshop
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb

  redis:
    image: redis
    container_name: redis
    networks:
      - roboshop

  user:
    image: user:v1
    container_name: user
    networks:
      - roboshop
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGO_HOST=mongodb
      - REDIS_HOST=redis

  cart:
    image: cart:v1
    container_name: cart
    networks:
      - roboshop
    depends_on:
      - redis
      - catalogue
    environment:
      - REDIS_HOST=redis
      - CATALOGUE_HOST=catalogue

  mysql:
    image: joindevops/mysql:v1
    container_name: mysql
    networks:
      - roboshop
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=yourRootPassword  # Change to secure password
      - MYSQL_DATABASE=roboshop

  shipping:
    image: joindevops/shipping:v1
    container_name: shipping
    networks:
      - roboshop
    depends_on:
      - cart
      - mysql
    environment:
      - CART_ENDPOINT=cart:8080
      - DB_HOST=mysql

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    networks:
      - roboshop
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=roboshop
      - RABBITMQ_DEFAULT_PASS=roboshop123

  payment:
    build:
      context: ./payment
    container_name: payment
    networks:
      - roboshop
    depends_on:
      - cart
      - user
      - rabbitmq
    environment:
      - CART_HOST=cart
      - USER_HOST=user
      - RABBITMQ_HOST=rabbitmq

  web:
    image: web:v1
    container_name: web
    networks:
      - roboshop
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - user
      - cart
      - shipping
      - payment

volumes:
  mysql:
  rabbitmq:
