
networks:
  roboshop:
    driver: bridge

volumes:
  mongodb:
  redis:
  mysql:
  rabbitmq:

services:
  mongodb:
    image: mongodb:v1
    container_name: mongodb
    networks:
      - roboshop
    volumes:
      - source: mongodb
        target: /data/db
        type: volume

  catalogue:
    image: catalogue:v1
    container_name: catalogue
    networks:
      - roboshop
    depends_on:
      - mongodb

  redis:
    image: redis
    container_name: redis
    networks:
      - roboshop
    ports:
      - "6379:6379"  
    volumes:
      - source: redis
        target: /data
        type: volume

  user:
    image: user:v1
    container_name: user
    networks:
      - roboshop
    depends_on:
      - mongodb
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  cart:
    image: cart:v1
    container_name: cart
    networks:
      - roboshop
    depends_on:
      - redis
      - catalogue
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  mysql:
    image: mysql:5.7
    container_name: mysql
    networks:
      - roboshop
    
      
    volumes:
      - mysql:/var/lib/mysql
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  

  shipping:
  image: shipping:v1
  container_name: shipping
  networks:
    - roboshop
  depends_on:
    - cart
    - mysql
  ulimits:
    nofile:
      soft: 65536
      hard: 65536
  mem_limit: 2g



  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    networks:
      - roboshop
    volumes:
      - source: rabbitmq
        target: /var/lib/rabbitmq
        type: volume
    environment:
      - RABBITMQ_DEFAULT_USER=roboshop
      - RABBITMQ_DEFAULT_PASS=roboshop123

  payment:
    image: payment:v1
    container_name: payment
    networks:
      - roboshop
    depends_on:
      - cart
      - user
      - rabbitmq

  web:
    image: web:v1
    container_name: web
    networks:
      - roboshop
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - user
      - cart
      - shipping
      - payment
